#!/bin/bash
if [ "${1}" ]; then
    seed=`grep root: /etc/shadow | awk -F\$ '{print $3}'`
    pw=${1}
    pw1=`python -c "import crypt, getpass, pwd; print crypt.crypt('${pw}', '\\$6\\$${seed}\\$')"`
    grep -m1 -q "root:${pw1}" /etc/shadow
    exit $?
else
    exit 1
fi
