#!/bin/bash
if [ -n "${1}" ]; then
    seed=$(grep root: /etc/shadow | awk -F\$ '{print $3}')
    seed=$(echo -e -n "\$6\$${seed}")
    pw=${1}
    pw1=$(python -c 'import crypt; print crypt.crypt("'"${pw}"'", "'"${seed}"'")')
    grep -m1 -q "root:${pw1}" /etc/shadow
    exit $?
else
    exit 1
fi
