#!/bin/sh
# erland hack
# http://www.ewdisonthen.com/how-to-setup-pptp-vpn-server-on-linux-tutorial-07577.php
exit 0
echo $* >/tmp/junk
env >>/tmp/junk
sleep 1
LCK=/tmp/forward_$PPP_IFACE
if [ -f $LCK ]; then exit 0; fi
NET="`echo $PPP_LOCAL | cut -d. -f1-3`.0/24"
LIF=`route -n | grep UG | awk '{print $8}'`
/sbin/iptables -t nat -A POSTROUTING -s $NET -o $LIF -j MASQUERADE
/sbin/iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -i $PPP_IFACE -j TCPMSS --set-mss 1356
touch $LCK
echo "---" >> /tmp/junk
echo "net=$NET, lif=$LIF, ppp_iface=$PPP_IFACE" >> /tmp/junk
exit 0
